#!/usr/bin/env bash
# Disclaimer: NEVER IN YOUR LIFE try this script with *HIGHLY* generic name like 'kernel' or 'lib'
# There are so many iterations that you don't even need this script timewise
# It's only for convenience to have one package-pattern added in the sisy DB, not really more
export PACKAGE_LIST="$@"

 for i in "${PACKAGE_LIST}" ; do

  if [[ "$0" == "sisy-single-spmsync" ]] || [[ "$0" == "sisy-single-spmsync.py" ]] || \
    [[ "$0" == "./sisy-single-spmsync" ]] || [[ "$0" == "make_singlepkg_spmsync_csv" ]] \
    || [[ "$0" = "./make_singlepkg_spmsync_csv" ]] || [[ "$0" == "/usr/share/sisyphus/helpers/make_singlepkg_spmsync_csv" ]] \
    && [[ "$1" == "spmsync-pkg" ]] ; then
   for z in "${@:1}" ; do

     for e in ${@:2} ; do

      export SORTED_PKG_ELEMENTS="$(qlist -ICv | grep $e)"

      if [[ -z "${SORTED_PKG_ELEMENTS}" ]] ; then
        echo "Package $e not installed"
        echo "Skipping $e"
        echo " "
      else
#        echo "Multiple package with the same name detected. Better try with version also."
#        echo "And because we are extremely lazy to implement some special method of getting the available"
#        echo "packages and comparing them with what you inserted in the input, we will just take all the"
#        echo "available and installed package with the same name and put them into sisy database."

       for x in $(find /var/db/pkg/ -iname "*$e*" | cut -d "/" -f5 | sort -u) ; do
          if [[ ! -e "/var/db/pkg/$x" ]] ; then
            echo "Hmm... seems your package $x does not have a database folder"
            echo " "
          else
            for d in $(qlist -ICv | grep $e ) ; do
              pushd /var/db/pkg/"${d}" > /dev/null 2>&1
              echo "$(<CATEGORY),$(sed -re "s/-([0-9])/,\1/" <PF),$(<SLOT),$(<BUILD_TIME),$(sed -e "s/\"//g" -e "s/\'//g" -e "s/\,//g" <DESCRIPTION)" >> /tmp/portage_singlepkg_spmsync.csv
              sort -u /tmp/portage_singlepkg_spmsync.csv -o /tmp/portage_singlepkg_spmsync.csv
              popd > /dev/null 2>&1
            done
          fi
       done
      fi
     done
   done
  fi
done

if [[ -e "/tmp/portage_singlepkg_spmsync.csv" ]] ; then
  mv /tmp/portage_singlepkg_spmsync.csv /var/lib/sisyphus/csv/portage_singlepkg_spmsync.csv || exit 1
else
  echo "Re-run the script, the source portage_singlepkg_spmsync.csv file not found"
  echo " "
  exit 1
fi

rm -rf /tmp/portage_singlepkg_spmsync.csv || exit 1
